# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	penbsd-desktop	
PORTVERSION=	0.18
CATEGORIES=	x11

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	PenBSD Desktop Port

RUN_DEPENDS=	font-awesome>0:x11-fonts/font-awesome \
		i3:x11-wm/i3 \
		st:x11/i3-sterm \
		dunst:sysutils/dunst \
		rofi:x11/rofi \
		feh:graphics/feh \
		py3status:deskutils/py-py3status \
		notify-send:devel/libnotify \
		compton:x11-wm/compton \
		ranger:sysutils/py-ranger \
		i3status:x11/i3status

USES=		metaport fonts
NO_ARCH=	yes

.include <bsd.port.mk>
