# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	devtools
PORTVERSION=	0.3
CATEGORIES=	base misc

MAINTAINER=	miwi@FreeBSD.org
COMMENT=	Devtools Port

RUN_DEPENDS=	autoconf>=2.69:devel/autoconf \
 	        automake>=1.16.1:devel/automake \
		arc:devel/arcanist \
		gmake:devel/gmake \
		libtool:devel/libtool \
		cmake:devel/cmake \
		gettext:devel/gettext-tools \
		bash:shells/bash \
		bison:devel/bison \
		curl:ftp/curl


USES=		metaport
NO_ARCH=	yes


.include <bsd.port.mk>
